# Generated by Django 3.0 on 2019-12-16 13:35

import DataBrowse.validaotrs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframetif',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[DataBrowse.validaotrs.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='TIFProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('source_TIF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBrowse.DataFrameTIF')),
            ],
        ),
    ]
