# Generated by Django 3.0 on 2019-12-17 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0002_auto_20191216_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataframetif',
            name='sequence_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
