# Generated by Django 3.0 on 2019-12-17 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0003_dataframetif_sequence_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframetif',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded'),
        ),
    ]
