# Generated by Django 3.0 on 2019-12-19 02:20

import DataBrowse.models
import DataBrowse.validaotrs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0004_auto_20191218_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframetif',
            name='upload',
            field=models.FileField(upload_to=DataBrowse.models.generate_save_path, validators=[DataBrowse.validaotrs.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='JPEGPageFromTIF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_location', models.ImageField(upload_to='')),
                ('page_id', models.IntegerField()),
                ('source_TIF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBrowse.DataFrameTIF')),
            ],
        ),
    ]
