# Generated by Django 3.0 on 2019-12-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0005_auto_20191219_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpegpagefromtif',
            name='page_location',
            field=models.ImageField(max_length=1000, upload_to=''),
        ),
    ]
