# Generated by Django 3.0 on 2019-12-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0007_auto_20191219_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpegpagefromtif',
            name='page_location',
            field=models.FileField(max_length=1000, upload_to='xx/static'),
        ),
    ]
