# Generated by Django 3.0 on 2020-02-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0008_auto_20191219_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpegpagefromtif',
            name='page_location',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
        migrations.CreateModel(
            name='TIFResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_source', models.FileField(max_length=1000, upload_to='')),
                ('result_type', models.FileField(max_length=1000, upload_to='')),
                ('result_location', models.FileField(max_length=1000, upload_to='')),
                ('source_TIF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBrowse.DataFrameTIF')),
            ],
        ),
    ]
