# Generated by Django 3.0 on 2020-02-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0009_auto_20200227_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='tifresult',
            name='result_url',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tifresult',
            name='result_source',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tifresult',
            name='result_type',
            field=models.CharField(max_length=1000),
        ),
    ]
