# Generated by Django 3.0 on 2020-02-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0010_auto_20200227_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tifresult',
            old_name='result_url',
            new_name='result_value',
        ),
    ]
