# Generated by Django 3.0 on 2020-02-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0011_auto_20200227_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tifresult',
            name='result_value',
            field=models.TextField(),
        ),
    ]
