# Generated by Django 3.0.5 on 2020-06-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBrowse', '0012_auto_20200229_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataframetif',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
